# =============================================================================
# ticker_db.py — Baza tickerów dla beta1 Portfolio Tracker
# Kompletna baza: S&P 500, GPW (WIG20+mWIG40+sWIG80+), UK FTSE, Krypto
# =============================================================================

# Format: "TICKER — Nazwa" : "ticker_yfinance"

TICKER_DATABASE = {
    # =========================================================================
    # 🪙 KRYPTOWALUTY (Top 20)
    # =========================================================================
    "BTC-USD — Bitcoin": "BTC-USD",
    "ETH-USD — Ethereum": "ETH-USD",
    "BNB-USD — Binance Coin": "BNB-USD",
    "XRP-USD — Ripple": "XRP-USD",
    "ADA-USD — Cardano": "ADA-USD",
    "SOL-USD — Solana": "SOL-USD",
    "DOGE-USD — Dogecoin": "DOGE-USD",
    "DOT-USD — Polkadot": "DOT-USD",
    "AVAX-USD — Avalanche": "AVAX-USD",
    "POL-USD — Polygon (MATIC)": "POL-USD",
    "LINK-USD — Chainlink": "LINK-USD",
    "ATOM-USD — Cosmos": "ATOM-USD",
    "UNI7083-USD — Uniswap": "UNI7083-USD",
    "LTC-USD — Litecoin": "LTC-USD",
    "FIL-USD — Filecoin": "FIL-USD",
    "APT21794-USD — Aptos": "APT21794-USD",
    "NEAR-USD — NEAR Protocol": "NEAR-USD",
    "ARB11841-USD — Arbitrum": "ARB11841-USD",
    "OP-USD — Optimism": "OP-USD",
    "SUI20947-USD — Sui": "SUI20947-USD",

    # =========================================================================
    # 🇺🇸 US STOCKS — S&P 500 + Nasdaq + popularne
    # =========================================================================
    # --- Technologia ---
    "AAPL — Apple Inc.": "AAPL",
    "MSFT — Microsoft Corp.": "MSFT",
    "GOOGL — Alphabet (Google) Class A": "GOOGL",
    "GOOG — Alphabet (Google) Class C": "GOOG",
    "AMZN — Amazon.com Inc.": "AMZN",
    "NVDA — NVIDIA Corp.": "NVDA",
    "META — Meta Platforms (Facebook)": "META",
    "TSLA — Tesla Inc.": "TSLA",
    "AVGO — Broadcom Inc.": "AVGO",
    "ORCL — Oracle Corp.": "ORCL",
    "ADBE — Adobe Inc.": "ADBE",
    "CRM — Salesforce Inc.": "CRM",
    "AMD — Advanced Micro Devices": "AMD",
    "INTC — Intel Corp.": "INTC",
    "CSCO — Cisco Systems": "CSCO",
    "QCOM — Qualcomm Inc.": "QCOM",
    "TXN — Texas Instruments": "TXN",
    "AMAT — Applied Materials": "AMAT",
    "MU — Micron Technology": "MU",
    "LRCX — Lam Research": "LRCX",
    "KLAC — KLA Corp.": "KLAC",
    "SNPS — Synopsys Inc.": "SNPS",
    "CDNS — Cadence Design Systems": "CDNS",
    "MRVL — Marvell Technology": "MRVL",
    "ADI — Analog Devices": "ADI",
    "NXPI — NXP Semiconductors": "NXPI",
    "ON — ON Semiconductor": "ON",
    "MPWR — Monolithic Power Systems": "MPWR",
    "SWKS — Skyworks Solutions": "SWKS",
    "MCHP — Microchip Technology": "MCHP",
    "FTNT — Fortinet Inc.": "FTNT",
    "PANW — Palo Alto Networks": "PANW",
    "CRWD — CrowdStrike Holdings": "CRWD",
    "ZS — Zscaler Inc.": "ZS",
    "NET — Cloudflare Inc.": "NET",
    "DDOG — Datadog Inc.": "DDOG",
    "SNOW — Snowflake Inc.": "SNOW",
    "MDB — MongoDB Inc.": "MDB",
    "WDAY — Workday Inc.": "WDAY",
    "NOW — ServiceNow Inc.": "NOW",
    "INTU — Intuit Inc.": "INTU",
    "TEAM — Atlassian Corp.": "TEAM",
    "ZM — Zoom Video Communications": "ZM",
    "DOCU — DocuSign Inc.": "DOCU",
    "TWLO — Twilio Inc.": "TWLO",
    "OKTA — Okta Inc.": "OKTA",
    "SQ — Block Inc. (Square)": "SQ",
    "SHOP — Shopify Inc.": "SHOP",
    "PYPL — PayPal Holdings": "PYPL",
    "COIN — Coinbase Global": "COIN",
    "HOOD — Robinhood Markets": "HOOD",
    "SOFI — SoFi Technologies": "SOFI",
    "PLTR — Palantir Technologies": "PLTR",
    "PATH — UiPath Inc.": "PATH",
    "AI — C3.ai Inc.": "AI",
    "BBAI — BigBear.ai Holdings": "BBAI",
    "IONQ — IonQ Inc.": "IONQ",
    "RGTI — Rigetti Computing": "RGTI",
    "IBM — IBM Corp.": "IBM",
    "HPQ — HP Inc.": "HPQ",
    "HPE — Hewlett Packard Enterprise": "HPE",
    "DELL — Dell Technologies": "DELL",
    "WDC — Western Digital": "WDC",
    "STX — Seagate Technology": "STX",
    "SMCI — Super Micro Computer": "SMCI",
    "ARM — Arm Holdings": "ARM",
    "CRSP — CRISPR Therapeutics": "CRSP",
    # --- Finanse ---
    "JPM — JPMorgan Chase & Co.": "JPM",
    "BAC — Bank of America": "BAC",
    "WFC — Wells Fargo & Co.": "WFC",
    "GS — Goldman Sachs Group": "GS",
    "MS — Morgan Stanley": "MS",
    "C — Citigroup Inc.": "C",
    "BRK-B — Berkshire Hathaway Class B": "BRK-B",
    "V — Visa Inc.": "V",
    "MA — Mastercard Inc.": "MA",
    "AXP — American Express": "AXP",
    "BLK — BlackRock Inc.": "BLK",
    "SCHW — Charles Schwab": "SCHW",
    "COF — Capital One Financial": "COF",
    "USB — U.S. Bancorp": "USB",
    "PNC — PNC Financial Services": "PNC",
    "TFC — Truist Financial": "TFC",
    "BK — Bank of New York Mellon": "BK",
    "STT — State Street Corp.": "STT",
    "CME — CME Group Inc.": "CME",
    "ICE — Intercontinental Exchange": "ICE",
    "SPGI — S&P Global Inc.": "SPGI",
    "MCO — Moody's Corp.": "MCO",
    "MSCI — MSCI Inc.": "MSCI",
    "MMC — Marsh & McLennan": "MMC",
    "AON — Aon plc": "AON",
    "AIG — American International Group": "AIG",
    "MET — MetLife Inc.": "MET",
    "PRU — Prudential Financial": "PRU",
    "ALL — Allstate Corp.": "ALL",
    "TRV — Travelers Companies": "TRV",
    "CB — Chubb Limited": "CB",
    "AFLAC — Aflac Inc.": "AFL",
    # --- Zdrowie ---
    "JNJ — Johnson & Johnson": "JNJ",
    "UNH — UnitedHealth Group": "UNH",
    "PFE — Pfizer Inc.": "PFE",
    "MRK — Merck & Co.": "MRK",
    "LLY — Eli Lilly & Co.": "LLY",
    "ABBV — AbbVie Inc.": "ABBV",
    "TMO — Thermo Fisher Scientific": "TMO",
    "ABT — Abbott Laboratories": "ABT",
    "DHR — Danaher Corp.": "DHR",
    "BMY — Bristol-Myers Squibb": "BMY",
    "AMGN — Amgen Inc.": "AMGN",
    "GILD — Gilead Sciences": "GILD",
    "VRTX — Vertex Pharmaceuticals": "VRTX",
    "REGN — Regeneron Pharmaceuticals": "REGN",
    "ISRG — Intuitive Surgical": "ISRG",
    "MDT — Medtronic plc": "MDT",
    "SYK — Stryker Corp.": "SYK",
    "BSX — Boston Scientific": "BSX",
    "EW — Edwards Lifesciences": "EW",
    "ZBH — Zimmer Biomet": "ZBH",
    "CI — Cigna Group": "CI",
    "ELV — Elevance Health": "ELV",
    "CVS — CVS Health Corp.": "CVS",
    "HCA — HCA Healthcare": "HCA",
    "HUM — Humana Inc.": "HUM",
    "CNC — Centene Corp.": "CNC",
    "MRNA — Moderna Inc.": "MRNA",
    "BNTX — BioNTech SE": "BNTX",
    "BIIB — Biogen Inc.": "BIIB",
    "ILMN — Illumina Inc.": "ILMN",
    "IQV — IQVIA Holdings": "IQV",
    "A — Agilent Technologies": "A",
    "DXCM — DexCom Inc.": "DXCM",
    "ALGN — Align Technology": "ALGN",
    "HOLX — Hologic Inc.": "HOLX",
    "IDXX — IDEXX Laboratories": "IDXX",
    "VEEV — Veeva Systems": "VEEV",
    # --- Konsumpcja ---
    "WMT — Walmart Inc.": "WMT",
    "COST — Costco Wholesale": "COST",
    "HD — Home Depot Inc.": "HD",
    "LOW — Lowe's Companies": "LOW",
    "TGT — Target Corp.": "TGT",
    "PG — Procter & Gamble": "PG",
    "KO — Coca-Cola Co.": "KO",
    "PEP — PepsiCo Inc.": "PEP",
    "PM — Philip Morris International": "PM",
    "MO — Altria Group": "MO",
    "CL — Colgate-Palmolive": "CL",
    "KMB — Kimberly-Clark": "KMB",
    "MDLZ — Mondelez International": "MDLZ",
    "KHC — Kraft Heinz Co.": "KHC",
    "GIS — General Mills": "GIS",
    "K — Kellanova": "K",
    "HSY — Hershey Co.": "HSY",
    "SJM — J.M. Smucker Co.": "SJM",
    "CAG — Conagra Brands": "CAG",
    "TSN — Tyson Foods": "TSN",
    "HRL — Hormel Foods": "HRL",
    "CPB — Campbell Soup": "CPB",
    "STZ — Constellation Brands": "STZ",
    "BUD — Anheuser-Busch InBev": "BUD",
    "DEO — Diageo plc (ADR)": "DEO",
    "EL — Estée Lauder": "EL",
    "NKE — Nike Inc.": "NKE",
    "LULU — Lululemon Athletica": "LULU",
    "TJX — TJX Companies": "TJX",
    "ROST — Ross Stores": "ROST",
    "DG — Dollar General": "DG",
    "DLTR — Dollar Tree": "DLTR",
    "SBUX — Starbucks Corp.": "SBUX",
    "MCD — McDonald's Corp.": "MCD",
    "YUM — Yum! Brands": "YUM",
    "CMG — Chipotle Mexican Grill": "CMG",
    "DPZ — Domino's Pizza": "DPZ",
    "DASH — DoorDash Inc.": "DASH",
    "UBER — Uber Technologies": "UBER",
    "LYFT — Lyft Inc.": "LYFT",
    "ABNB — Airbnb Inc.": "ABNB",
    "BKNG — Booking Holdings": "BKNG",
    "EXPE — Expedia Group": "EXPE",
    "MAR — Marriott International": "MAR",
    "HLT — Hilton Worldwide": "HLT",
    "DIS — Walt Disney Co.": "DIS",
    "NFLX — Netflix Inc.": "NFLX",
    "PARA — Paramount Global": "PARA",
    "WBD — Warner Bros. Discovery": "WBD",
    "LYV — Live Nation Entertainment": "LYV",
    "SPOT — Spotify Technology": "SPOT",
    "RBLX — Roblox Corp.": "RBLX",
    "EA — Electronic Arts": "EA",
    "TTWO — Take-Two Interactive": "TTWO",
    "ATVI — Activision Blizzard": "ATVI",
    # --- Przemysł ---
    "CAT — Caterpillar Inc.": "CAT",
    "DE — Deere & Company": "DE",
    "HON — Honeywell International": "HON",
    "GE — General Electric": "GE",
    "BA — Boeing Co.": "BA",
    "RTX — RTX Corp. (Raytheon)": "RTX",
    "LMT — Lockheed Martin": "LMT",
    "NOC — Northrop Grumman": "NOC",
    "GD — General Dynamics": "GD",
    "LHX — L3Harris Technologies": "LHX",
    "UPS — United Parcel Service": "UPS",
    "FDX — FedEx Corp.": "FDX",
    "UNP — Union Pacific": "UNP",
    "CSX — CSX Corp.": "CSX",
    "NSC — Norfolk Southern": "NSC",
    "MMM — 3M Company": "MMM",
    "EMR — Emerson Electric": "EMR",
    "ITW — Illinois Tool Works": "ITW",
    "ROK — Rockwell Automation": "ROK",
    "ETN — Eaton Corp.": "ETN",
    "PH — Parker-Hannifin": "PH",
    "IR — Ingersoll Rand": "IR",
    "CMI — Cummins Inc.": "CMI",
    "PCAR — PACCAR Inc.": "PCAR",
    "FAST — Fastenal Co.": "FAST",
    "ROP — Roper Technologies": "ROP",
    "ACN — Accenture plc": "ACN",
    "WM — Waste Management": "WM",
    "RSG — Republic Services": "RSG",
    "VRSK — Verisk Analytics": "VRSK",
    "CTAS — Cintas Corp.": "CTAS",
    "PAYX — Paychex Inc.": "PAYX",
    "ADP — Automatic Data Processing": "ADP",
    # --- Energia ---
    "XOM — Exxon Mobil Corp.": "XOM",
    "CVX — Chevron Corp.": "CVX",
    "COP — ConocoPhillips": "COP",
    "EOG — EOG Resources": "EOG",
    "SLB — Schlumberger (SLB)": "SLB",
    "MPC — Marathon Petroleum": "MPC",
    "VLO — Valero Energy": "VLO",
    "PSX — Phillips 66": "PSX",
    "OXY — Occidental Petroleum": "OXY",
    "PXD — Pioneer Natural Resources": "PXD",
    "DVN — Devon Energy": "DVN",
    "HAL — Halliburton Co.": "HAL",
    "FANG — Diamondback Energy": "FANG",
    "KMI — Kinder Morgan": "KMI",
    "WMB — Williams Companies": "WMB",
    "OKE — ONEOK Inc.": "OKE",
    "TRGP — Targa Resources": "TRGP",
    "BKR — Baker Hughes": "BKR",
    # --- Nieruchomości (REITs) ---
    "AMT — American Tower Corp.": "AMT",
    "CCI — Crown Castle International": "CCI",
    "PLD — Prologis Inc.": "PLD",
    "EQIX — Equinix Inc.": "EQIX",
    "SPG — Simon Property Group": "SPG",
    "PSA — Public Storage": "PSA",
    "O — Realty Income Corp.": "O",
    "VICI — VICI Properties": "VICI",
    "DLR — Digital Realty Trust": "DLR",
    "WELL — Welltower Inc.": "WELL",
    "AVB — AvalonBay Communities": "AVB",
    "EQR — Equity Residential": "EQR",
    "VTR — Ventas Inc.": "VTR",
    "ARE — Alexandria Real Estate": "ARE",
    "MAA — Mid-America Apartment": "MAA",
    # --- Telekomunikacja ---
    "T — AT&T Inc.": "T",
    "VZ — Verizon Communications": "VZ",
    "TMUS — T-Mobile US": "TMUS",
    "CMCSA — Comcast Corp.": "CMCSA",
    "CHTR — Charter Communications": "CHTR",
    # --- Surowce ---
    "LIN — Linde plc": "LIN",
    "APD — Air Products & Chemicals": "APD",
    "SHW — Sherwin-Williams": "SHW",
    "ECL — Ecolab Inc.": "ECL",
    "DD — DuPont de Nemours": "DD",
    "DOW — Dow Inc.": "DOW",
    "NEM — Newmont Corp.": "NEM",
    "FCX — Freeport-McMoRan": "FCX",
    "PPG — PPG Industries": "PPG",
    "ALB — Albemarle Corp.": "ALB",
    "CF — CF Industries Holdings": "CF",
    "NUE — Nucor Corp.": "NUE",
    "STLD — Steel Dynamics": "STLD",
    "CLF — Cleveland-Cliffs": "CLF",
    "X — United States Steel": "X",
    # --- Utilities ---
    "NEE — NextEra Energy": "NEE",
    "DUK — Duke Energy": "DUK",
    "SO — Southern Company": "SO",
    "D — Dominion Energy": "D",
    "AEP — American Electric Power": "AEP",
    "EXC — Exelon Corp.": "EXC",
    "SRE — Sempra": "SRE",
    "XEL — Xcel Energy": "XEL",
    "ED — Consolidated Edison": "ED",
    "WEC — WEC Energy Group": "WEC",
    "ES — Eversource Energy": "ES",
    "AWK — American Water Works": "AWK",
    # --- Popularne / Trending ---
    "SNAP — Snap Inc.": "SNAP",
    "PINS — Pinterest Inc.": "PINS",
    "RIVN — Rivian Automotive": "RIVN",
    "LCID — Lucid Group": "LCID",
    "NIO — NIO Inc.": "NIO",
    "LI — Li Auto Inc.": "LI",
    "XPEV — XPeng Inc.": "XPEV",
    "MSTR — MicroStrategy": "MSTR",
    "GME — GameStop Corp.": "GME",
    "AMC — AMC Entertainment": "AMC",
    "BBBY — Bed Bath & Beyond": "BBBY",
    "BB — BlackBerry Ltd.": "BB",
    "TLRY — Tilray Brands": "TLRY",
    "SNDL — SNDL Inc.": "SNDL",
    "ZETA — Zeta Global Holdings": "ZETA",
    "APP — AppLovin Corp.": "APP",
    "DUOL — Duolingo Inc.": "DUOL",
    "MNDY — monday.com Ltd.": "MNDY",
    "CELH — Celsius Holdings": "CELH",
    "HIMS — Hims & Hers Health": "HIMS",
    "CAVA — CAVA Group": "CAVA",
    "BIRK — Birkenstock Holding": "BIRK",
    "ONON — On Holding AG": "ONON",
    "DKNG — DraftKings Inc.": "DKNG",
    "PENN — Penn Entertainment": "PENN",
    "WYNN — Wynn Resorts": "WYNN",
    "MGM — MGM Resorts": "MGM",
    "LVS — Las Vegas Sands": "LVS",
    "RCL — Royal Caribbean Group": "RCL",
    "CCL — Carnival Corp.": "CCL",
    "NCLH — Norwegian Cruise Line": "NCLH",
    "DAL — Delta Air Lines": "DAL",
    "UAL — United Airlines Holdings": "UAL",
    "LUV — Southwest Airlines": "LUV",
    "AAL — American Airlines": "AAL",
    "F — Ford Motor Co.": "F",
    "GM — General Motors": "GM",
    "STLA — Stellantis N.V.": "STLA",
    "TM — Toyota Motor Corp.": "TM",
    "HMC — Honda Motor Co.": "HMC",
    "RACE — Ferrari N.V.": "RACE",
    # --- ETFy ---
    "SPY — SPDR S&P 500 ETF": "SPY",
    "QQQ — Invesco QQQ (Nasdaq 100)": "QQQ",
    "VOO — Vanguard S&P 500 ETF": "VOO",
    "VTI — Vanguard Total Stock Market ETF": "VTI",
    "IWM — iShares Russell 2000 ETF": "IWM",
    "DIA — SPDR Dow Jones ETF": "DIA",
    "ARKK — ARK Innovation ETF": "ARKK",
    "GLD — SPDR Gold Shares ETF": "GLD",
    "SLV — iShares Silver Trust ETF": "SLV",
    "USO — United States Oil Fund ETF": "USO",
    "XLF — Financial Select Sector SPDR": "XLF",
    "XLE — Energy Select Sector SPDR": "XLE",
    "XLK — Technology Select Sector SPDR": "XLK",
    "XLV — Health Care Select Sector SPDR": "XLV",
    "XLI — Industrial Select Sector SPDR": "XLI",
    "SOXX — iShares Semiconductor ETF": "SOXX",
    "TLT — iShares 20+ Year Treasury Bond": "TLT",
    "HYG — iShares High Yield Corporate Bond": "HYG",
    "EEM — iShares MSCI Emerging Markets ETF": "EEM",
    "VWO — Vanguard FTSE Emerging Markets ETF": "VWO",
    "EFA — iShares MSCI EAFE ETF": "EFA",

    # =========================================================================
    # 🇵🇱 GPW — WIG20 + mWIG40 + sWIG80 + inne
    # =========================================================================
    # --- WIG20 ---
    "ALE.WA — Allegro": "ALE.WA",
    "ALC.WA — Alior Bank": "ALC.WA",
    "CCC.WA — CCC SA": "CCC.WA",
    "CDR.WA — CD Projekt": "CDR.WA",
    "CPS.WA — Cyfrowy Polsat": "CPS.WA",
    "DNP.WA — Dino Polska": "DNP.WA",
    "JSW.WA — JSW SA": "JSW.WA",
    "KGH.WA — KGHM Polska Miedź": "KGH.WA",
    "KRU.WA — Kruk SA": "KRU.WA",
    "LPP.WA — LPP SA": "LPP.WA",
    "MBK.WA — mBank SA": "MBK.WA",
    "OPL.WA — Orange Polska": "OPL.WA",
    "PEO.WA — Pekao SA": "PEO.WA",
    "PGE.WA — PGE SA": "PGE.WA",
    "PKN.WA — PKN Orlen": "PKN.WA",
    "PKO.WA — PKO Bank Polski": "PKO.WA",
    "PZU.WA — PZU SA": "PZU.WA",
    "SPL.WA — Santander Bank Polska": "SPL.WA",
    "TPE.WA — Tauron Polska Energia": "TPE.WA",
    "PCO.WA — Pepco Group": "PCO.WA",
    # --- mWIG40 ---
    "11B.WA — 11 bit studios": "11B.WA",
    "AMC.WA — Amica SA": "AMC.WA",
    "ASB.WA — Asseco Poland": "ASB.WA",
    "ACP.WA — Asseco Central Europe": "ACP.WA",
    "ASE.WA — Asseco South Eastern Europe": "ASE.WA",
    "ATC.WA — Arctic Paper": "ATC.WA",
    "ATT.WA — Grupa Azoty": "ATT.WA",
    "BDX.WA — Budimex SA": "BDX.WA",
    "BNP.WA — BNPP Bank": "BNP.WA",
    "BFT.WA — Benefit Systems": "BFT.WA",
    "CAR.WA — Inter Cars": "CAR.WA",
    "CIG.WA — CI Games": "CIG.WA",
    "CLN.WA — Cognor Holding": "CLN.WA",
    "CMR.WA — Comarch SA": "CMR.WA",
    "DAT.WA — Datawalk SA": "DAT.WA",
    "DOM.WA — Dom Development": "DOM.WA",
    "DVL.WA — Develia SA": "DVL.WA",
    "EAT.WA — AmRest Holdings": "EAT.WA",
    "ECH.WA — Echo Investment": "ECH.WA",
    "ENA.WA — Enea SA": "ENA.WA",
    "EUR.WA — Eurocash SA": "EUR.WA",
    "GPN.WA — Grupa Pracuj": "GPN.WA",
    "GPW.WA — GPW SA": "GPW.WA",
    "GTC.WA — Globe Trade Centre": "GTC.WA",
    "HRS.WA — Huuuge Inc.": "HRS.WA",
    "ING.WA — ING Bank Śląski": "ING.WA",
    "KTY.WA — Kęty SA": "KTY.WA",
    "LVC.WA — LiveChat Software": "LVC.WA",
    "LWB.WA — Bogdanka SA": "LWB.WA",
    "MAB.WA — Mabion SA": "MAB.WA",
    "MIL.WA — Bank Millennium": "MIL.WA",
    "MLG.WA — ML System": "MLG.WA",
    "MRC.WA — Mercator Medical": "MRC.WA",
    "NEU.WA — Neuca SA": "NEU.WA",
    "OAT.WA — Oat SA": "OAT.WA",
    "PCR.WA — PCC Rokita": "PCR.WA",
    "PLY.WA — PlayWay SA": "PLY.WA",
    "SNK.WA — Sanok Rubber": "SNK.WA",
    "TEN.WA — Ten Square Games": "TEN.WA",
    "TXT.WA — Text SA (LiveChat)": "TXT.WA",
    "VRG.WA — VRG SA": "VRG.WA",
    "WPL.WA — Wirtualna Polska": "WPL.WA",
    "XTB.WA — XTB SA": "XTB.WA",
    "ZEP.WA — Żywiec SA": "ZEP.WA",
    # --- sWIG80 + inne ---
    "1AT.WA — Unity Group": "1AT.WA",
    "APR.WA — Apator SA": "APR.WA",
    "BHW.WA — Bank Handlowy": "BHW.WA",
    "BIO.WA — Bioton SA": "BIO.WA",
    "BOS.WA — BOŚ Bank": "BOS.WA",
    "BRS.WA — Boryszew SA": "BRS.WA",
    "BST.WA — Best SA": "BST.WA",
    "CDA.WA — CD Action (Gremi Media)": "CDA.WA",
    "CIE.WA — Ciech SA": "CIE.WA",
    "CMP.WA — Comp SA": "CMP.WA",
    "DCR.WA — Decora SA": "DCR.WA",
    "DNR.WA — Dino Polska (alt)": "DNR.WA",
    "ENI.WA — Energoinstal SA": "ENI.WA",
    "ENG.WA — Energa SA": "ENG.WA",
    "FMF.WA — Famur SA": "FMF.WA",
    "FTE.WA — Forte SA": "FTE.WA",
    "GNB.WA — Getin Noble Bank": "GNB.WA",
    "GTN.WA — Getin Holding": "GTN.WA",
    "GRN.WA — Grodno SA": "GRN.WA",
    "HEL.WA — Helio SA": "HEL.WA",
    "IMP.WA — Impexmetal": "IMP.WA",
    "INK.WA — Instal Kraków": "INK.WA",
    "IPL.WA — IPOPEMA Securities": "IPL.WA",
    "IZB.WA — Izoblok SA": "IZB.WA",
    "KER.WA — Kernel Holding": "KER.WA",
    "KPD.WA — Korporacja KGL": "KPD.WA",
    "KRK.WA — Krakchemia": "KRK.WA",
    "KST.WA — Konsorcjum Stali": "KST.WA",
    "KVT.WA — Kino Polska": "KVT.WA",
    "LAB.WA — Labo Print": "LAB.WA",
    "LBW.WA — Lubelski Węgiel Bogdanka": "LBW.WA",
    "LEN.WA — Lena Lighting": "LEN.WA",
    "LKD.WA — Lokum Deweloper": "LKD.WA",
    "LTX.WA — Lentex SA": "LTX.WA",
    "MAK.WA — Makarony Polskie": "MAK.WA",
    "MCI.WA — MCI Capital": "MCI.WA",
    "MDG.WA — Medicalgorithmics": "MDG.WA",
    "MEX.WA — Mexpolbud": "MEX.WA",
    "MIR.WA — Miraculum": "MIR.WA",
    "MLB.WA — Mleczarnia": "MLB.WA",
    "MOJ.WA — Monnari Trade": "MOJ.WA",
    "MON.WA — Mostostal Warszawa": "MON.WA",
    "MWT.WA — Mangata Holding": "MWT.WA",
    "OPN.WA — Oponeo.pl": "OPN.WA",
    "OVO.WA — OVS Group": "OVO.WA",
    "PBX.WA — Pekabex SA": "PBX.WA",
    "PEN.WA — Penetrator SA": "PEN.WA",
    "PKP.WA — PKP Cargo": "PKP.WA",
    "PRF.WA — Pozbud SA": "PRF.WA",
    "PRT.WA — Protektor SA": "PRT.WA",
    "PWX.WA — Polwax SA": "PWX.WA",
    "QRS.WA — QRS SA": "QRS.WA",
    "RBW.WA — Rainbow Tours": "RBW.WA",
    "RFK.WA — Rafako SA": "RFK.WA",
    "RPC.WA — Relpol SA": "RPC.WA",
    "RVU.WA — R22 SA": "RVU.WA",
    "SEL.WA — SELENA FM": "SEL.WA",
    "SFG.WA — Sfinks Polska": "SFG.WA",
    "SLV.WA — Silvair": "SLV.WA",
    "SNS.WA — Sygnity SA": "SNS.WA",
    "STP.WA — STALPROFIL": "STP.WA",
    "STX.WA — Stalexport Autostrady": "STX.WA",
    "SWG.WA — Śnieżka SA": "SWG.WA",
    "TOR.WA — Torpol SA": "TOR.WA",
    "TOW.WA — Tower Investments": "TOW.WA",
    "TRK.WA — Trakcja SA": "TRK.WA",
    "ULG.WA — Ulma Construccion": "ULG.WA",
    "UNI.WA — Unimot SA": "UNI.WA",
    "VGO.WA — Vigo Photonics": "VGO.WA",
    "VOX.WA — Voxel SA": "VOX.WA",
    "WLT.WA — Wielton SA": "WLT.WA",
    "WTN.WA — Wittchen SA": "WTN.WA",
    "ZAP.WA — Zamet Industry": "ZAP.WA",
    "ZWC.WA — Zywiec Zdroj": "ZWC.WA",

    # =========================================================================
    # 🇬🇧 UK STOCKS (FTSE 100 + FTSE 250 główne)
    # =========================================================================
    "VOD.L — Vodafone Group": "VOD.L",
    "BARC.L — Barclays plc": "BARC.L",
    "HSBA.L — HSBC Holdings": "HSBA.L",
    "BP.L — BP plc": "BP.L",
    "SHEL.L — Shell plc": "SHEL.L",
    "GSK.L — GSK plc": "GSK.L",
    "AZN.L — AstraZeneca": "AZN.L",
    "ULVR.L — Unilever plc": "ULVR.L",
    "RIO.L — Rio Tinto": "RIO.L",
    "LLOY.L — Lloyds Banking Group": "LLOY.L",
    "GLEN.L — Glencore plc": "GLEN.L",
    "BT-A.L — BT Group": "BT-A.L",
    "NG.L — National Grid": "NG.L",
    "LSEG.L — London Stock Exchange Group": "LSEG.L",
    "RKT.L — Reckitt Benckiser": "RKT.L",
    "REL.L — RELX plc": "REL.L",
    "CPG.L — Compass Group": "CPG.L",
    "DGE.L — Diageo plc": "DGE.L",
    "BA.L — BAE Systems": "BA.L",
    "RR.L — Rolls-Royce Holdings": "RR.L",
    "AAL.L — Anglo American": "AAL.L",
    "ANTO.L — Antofagasta plc": "ANTO.L",
    "ABF.L — Associated British Foods": "ABF.L",
    "AUTO.L — Auto Trader Group": "AUTO.L",
    "AV.L — Aviva plc": "AV.L",
    "BME.L — B&M European Value Retail": "BME.L",
    "BDEV.L — Barratt Developments": "BDEV.L",
    "BKG.L — Berkeley Group": "BKG.L",
    "BNZL.L — Bunzl plc": "BNZL.L",
    "BRBY.L — Burberry Group": "BRBY.L",
    "CNA.L — Centrica plc": "CNA.L",
    "CCH.L — Coca-Cola HBC": "CCH.L",
    "CRH.L — CRH plc": "CRH.L",
    "CRDA.L — Croda International": "CRDA.L",
    "DCC.L — DCC plc": "DCC.L",
    "EVR.L — Evraz plc": "EVR.L",
    "EXPN.L — Experian plc": "EXPN.L",
    "FLTR.L — Flutter Entertainment": "FLTR.L",
    "FRES.L — Fresnillo plc": "FRES.L",
    "HIK.L — Hikma Pharmaceuticals": "HIK.L",
    "HLMA.L — Halma plc": "HLMA.L",
    "HL.L — Hargreaves Lansdown": "HL.L",
    "HWDN.L — Howden Joinery": "HWDN.L",
    "IAG.L — Int. Airlines Group": "IAG.L",
    "IHG.L — IHG Hotels & Resorts": "IHG.L",
    "III.L — 3i Group": "III.L",
    "IMB.L — Imperial Brands": "IMB.L",
    "INF.L — Informa plc": "INF.L",
    "ITRK.L — Intertek Group": "ITRK.L",
    "JD.L — JD Sports Fashion": "JD.L",
    "KGF.L — Kingfisher plc": "KGF.L",
    "LAND.L — Land Securities Group": "LAND.L",
    "LGEN.L — Legal & General Group": "LGEN.L",
    "MNG.L — M&G plc": "MNG.L",
    "MNDI.L — Mondi plc": "MNDI.L",
    "MRO.L — Melrose Industries": "MRO.L",
    "NWG.L — NatWest Group": "NWG.L",
    "OCDO.L — Ocado Group": "OCDO.L",
    "PHNX.L — Phoenix Group": "PHNX.L",
    "PRU.L — Prudential plc": "PRU.L",
    "PSN.L — Persimmon plc": "PSN.L",
    "PSON.L — Pearson plc": "PSON.L",
    "RMV.L — Rightmove plc": "RMV.L",
    "RTO.L — Rentokil Initial": "RTO.L",
    "SBRY.L — J Sainsbury plc": "SBRY.L",
    "SDR.L — Schroders plc": "SDR.L",
    "SGE.L — Sage Group": "SGE.L",
    "SGRO.L — Segro plc": "SGRO.L",
    "SHP.L — Shire plc": "SHP.L",
    "SKG.L — Smurfit Kappa Group": "SKG.L",
    "SMDS.L — Smith (DS) plc": "SMDS.L",
    "SMIN.L — Smiths Group": "SMIN.L",
    "SMT.L — Scottish Mortgage Inv. Trust": "SMT.L",
    "SN.L — Smith & Nephew": "SN.L",
    "SSE.L — SSE plc": "SSE.L",
    "STAN.L — Standard Chartered": "STAN.L",
    "SVT.L — Severn Trent": "SVT.L",
    "TSCO.L — Tesco plc": "TSCO.L",
    "TW.L — Taylor Wimpey": "TW.L",
    "UTLC.L — United Utilities Group": "UTLC.L",
    "UU.L — United Utilities": "UU.L",
    "WPP.L — WPP plc": "WPP.L",
    "WTB.L — Whitbread plc": "WTB.L",
}


def szukaj_tickery(zapytanie: str, limit: int = 15) -> list:
    """
    Wyszukuje tickery na podstawie zapytania (ticker lub nazwa spółki).
    Zwraca listę pasujących kluczy z TICKER_DATABASE.
    """
    if not zapytanie or len(zapytanie) < 1:
        return list(TICKER_DATABASE.keys())[:limit]

    zapytanie = zapytanie.upper().strip()
    wyniki = []

    # Najpierw: dokładne dopasowanie tickera
    for klucz, ticker in TICKER_DATABASE.items():
        if ticker.upper() == zapytanie:
            wyniki.insert(0, klucz)

    # Potem: ticker zaczyna się od zapytania
    for klucz, ticker in TICKER_DATABASE.items():
        if ticker.upper().startswith(zapytanie) and klucz not in wyniki:
            wyniki.append(klucz)

    # Na końcu: nazwa zawiera zapytanie
    for klucz in TICKER_DATABASE:
        if zapytanie in klucz.upper() and klucz not in wyniki:
            wyniki.append(klucz)

    return wyniki[:limit]
